FROM      centos
MAINTAINER Filirom1 <filirom1@gmail.com>

ADD . /app

RUN yum install -y epel-release
RUN yum install -y patch tar git ruby ruby-devel rubygem-bundler make gcc gcc-c++ zlib-devel nginx 

RUN cd /app  && bundle install

RUN cp /app/docker/unicorn/unicorn.conf /etc/nginx/conf.d/unicorn.conf && \
    cp /app/docker/unicorn/nginx.conf /etc/nginx/nginx.conf && \
    echo "daemon off;" >> /etc/nginx/nginx.conf

RUN mkdir -p /var/log/inventory && chmod o+rwX /var/log/inventory && \
    mkdir -p /var/lib/inventory/ && chmod o+rwX /var/lib/inventory && \
    mkdir -p /var/run/inventory/ && chmod o+rwX /var/run/inventory

EXPOSE 80
CMD    ["/app/docker/unicorn/run-unicorn.sh"]
