---
host: 127.0.0.1
smtp_port: 2525
max_connections: 4
debug: false
es_host: http://localhost:9200
es_index_prefix: inventory_
failed_facts_dir: /var/log/inventory/failures
logger: stdout
log_level: INFO
type_key: type
type_default: facts
version_key: version
version_default: 1-0-0
json_schema_dir: /etc/inventory/json_schema
plugins_path: 
plugins: 
- log_failures_on_disk
- facts_parser
- json_schema_validator
- index
